# Generated by Django 2.2.1 on 2019-05-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente_name', models.CharField(max_length=100, verbose_name='Nome Ingrediente')),
                ('ingredient_slug', models.SlugField(max_length=100, verbose_name='Identificador Ingrediente')),
                ('ingredient_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('ingredient_created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ingredient_modifed', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Lanches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanche_name', models.CharField(max_length=100, verbose_name='Nome do Lanche')),
                ('lanche_slug', models.SlugField(max_length=100, verbose_name='Identificador Lanche')),
                ('lanche_description', models.TextField(blank=True, verbose_name='Descricao')),
                ('lanche_created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lanche_modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ingredientes', models.ManyToManyField(to='cardapio.Ingredientes')),
            ],
            options={
                'verbose_name': 'Lanche',
                'verbose_name_plural': 'Lanches',
            },
        ),
    ]
