# Generated by Django 2.2.1 on 2019-05-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanches',
            name='imagem',
            field=models.ImageField(max_length=255, null=True, upload_to='imagens/'),
        ),
    ]
