# Generated by Django 2.2.1 on 2019-05-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_lanches_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientes',
            name='imagem',
            field=models.ImageField(max_length=255, null=True, upload_to='imagens/'),
        ),
    ]
