# Generated by Django 2.2.1 on 2019-05-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_ingredientes_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='imagem',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='lanches',
            name='imagem',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imagens/'),
        ),
    ]
